spring:
  ai:
    openai:
      base-url: ${MOCK_API_URL}

custom:
  rest-template:
    connect-timeout: 1000      # 연결 타임아웃(ms)
    read-timeout: 10000         # 응답 대기 시간(ms)
    max-total-connections: 800 # 전체 커넥션 수
    max-per-route: 800         # 호스트당 최대 커넥션 수

  async:
    core-pool-size: 100        # 항상 유지되는 최소 스레드 수
    max-pool-size: 300         # 최대 스레드 수. 요청이 너무 많고 큐까지 꽉 찼을 때
    queue-capacity: 1000
    thread-name-prefix: "AsyncThread-"